import { writeFileSync, existsSync, mkdirSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  KNOWLEDGE_DIR, REPO_MAP_PATH, SERVICE_DIR, ADR_DIR,
} from './config.js';
import type { ServiceInfo, GitCommit } from './types.js';

export function ensureDir(dir: string): void {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

export function writeRepoMap(services: ServiceInfo[]): void {
  let md = `# TrueVow Service Map\n\n`;
  md += `> Auto-generated by \`knowledge-sync\`. Last updated: ${new Date().toISOString().slice(0, 10)}\n\n`;
  md += `| Service | Port | Stack | Commits | Description |\n`;
  md += `|---------|------|-------|---------|-------------|\n`;

  for (const s of services) {
    const port = s.port ? String(s.port) : '—';
    const commits = s.commitCount !== undefined ? String(s.commitCount) : '—';
    const desc = s.description || '—';
    const link = `[[${s.name}]]`;
    const gitIcon = s.isGitRepo ? '✅' : '❌';
    md += `| ${link} ${gitIcon} | ${port} | ${s.stack} | ${commits} | ${desc} |\n`;
  }

  ensureDir(KNOWLEDGE_DIR);
  writeFileSync(REPO_MAP_PATH, md, 'utf-8');
  console.log('  ✓ REPO-MAP.md updated');
}

function findRelatedAdrs(serviceName: string): string[] {
  if (!existsSync(ADR_DIR)) return [];
  const files: string[] = [];
  try {
    const entries = readdirSync(ADR_DIR);
    for (const f of entries) {
      if (f.endsWith('.md')) {
        const content = readFileSync(join(ADR_DIR, f), 'utf-8');
        if (content.includes(serviceName)) files.push(f.replace('.md', ''));
      }
    }
  } catch { /* skip */ }
  return files;
}

export function writeServicePages(services: ServiceInfo[]): void {
  ensureDir(SERVICE_DIR);

  for (const s of services) {
    const slug = s.dirName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase().replace(/^-+|-+$/g, '');
    const filePath = join(SERVICE_DIR, `${slug}.md`);

    let md = `# ${s.name}\n\n`;
    md += `**Directory:** \`${s.dirName}\`\n`;
    md += `**Git:** ${s.isGitRepo ? `✅ ${s.commitCount} commits` : '❌ Not a repo'}\n\n`;
    md += s.description ? `${s.description}\n\n` : '';
    md += `| Attribute | Value |\n|-----------|-------|\n`;
    md += `| Stack | ${s.stack} |\n`;
    if (s.port) md += `| Port | ${s.port} |\n`;
    if (s.dependencies?.length) md += `| Key Dependencies | ${s.dependencies.slice(0, 8).join(', ')} |\n`;

    const adrs = findRelatedAdrs(s.name);
    if (adrs.length > 0) {
      md += `\n## Related Decisions\n`;
      for (const a of adrs) md += `- [[ADRs/${a}|${a}]]\n`;
    }

    md += `\n## Recent Activity\n`;
    md += `- See [[Session-Logs]] for session history\n`;

    writeFileSync(filePath, md, 'utf-8');
  }
  console.log(`  ✓ ${services.length} service pages written`);
}

export function writeGitSessionLog(serviceName: string, dirName: string, commits: GitCommit[]): string | null {
  if (commits.length === 0) return null;

  const today = new Date().toISOString().slice(0, 10);
  const logsDir = join(KNOWLEDGE_DIR, 'Session-Logs');
  ensureDir(logsDir);
  const filePath = join(logsDir, `${today}-git-ingest.md`);

  let md = `# Git Ingest — ${today}\n\n`;
  md += `## New Commits\n\n`;
  md += `| Service | Author | Message | Hash |\n`;
  md += `|---------|--------|---------|------|\n`;

  for (const c of commits) {
    const shortHash = c.hash.slice(0, 7);
    const message = c.message.length > 60 ? c.message.slice(0, 57) + '...' : c.message;
    md += `| [[${serviceName}]] | ${c.author} | ${message} | \`${shortHash}\` |\n`;
  }

  writeFileSync(filePath, md, 'utf-8');
  return filePath;
}

export function writeDailyActivitySummary(services: ServiceInfo[], allCommits: Map<string, GitCommit[]>): void {
  const today = new Date().toISOString().slice(0, 10);
  const summaryDir = join(KNOWLEDGE_DIR, 'Session-Logs');
  ensureDir(summaryDir);
  const filePath = join(summaryDir, `${today}-activity-summary.md`);

  let md = `# Activity Summary — ${today}\n\n`;

  let totalCommits = 0;
  for (const [, commits] of allCommits) totalCommits += commits.length;
  md += `**Services scanned:** ${services.length}\n`;
  md += `**Repos with git:** ${services.filter(s => s.isGitRepo).length}\n`;
  md += `**New commits found:** ${totalCommits}\n\n`;

  md += `## Commits by Service\n\n`;
  for (const s of services) {
    const commits = allCommits.get(s.dirName) || [];
    if (commits.length > 0) {
      md += `- [[${s.name}]] — ${commits.length} commit(s)\n`;
      for (const c of commits.slice(0, 3)) {
        md += `  - \`${c.hash.slice(0, 7)}\` ${c.message} (_${c.author}_, ${c.date.slice(0, 10)})\n`;
      }
    }
  }

  md += `\n## Config Changes\n`;
  md += `- Detected during scan — review [[Cross-Service]] for details\n`;

  writeFileSync(filePath, md, 'utf-8');
  console.log('  ✓ Daily activity summary written');
}
